apiVersion: v1
kind: Service
metadata: 
    name: myapp-service
spec:
    type: NodeClusterIPPort
    ports:
        -   targetPort: 80
            port: 80
    selector: 
        app: my-app-pod
        type: backend
